### PR TITLE
refactor: follow font weight guidance for syntax highlighting

### PR DESCRIPTION
**Pull request by lilidotshi**
Proposed PR to address issue: https://github.com/catppuccin/xcode/issues/13
|Frappé|Latte|
|-|-|
|Screenshot 2024-10-29 at 1 09 32 PM|Screenshot 2024-10-29 at 1 09 34 PM|
|Macchiato|Mocha|
|Screenshot 2024-10-29 at 1 09 41 PM|Screenshot 2024-10-29 at 1 09 43 PM|

### CODE REVIEW

**Comment by lilidotshi** [comment]
Any thoughts on this PR @quentinguidee ?

**Review by sgoudham — CHANGES_REQUESTED** [review]
Hey 👋,

I think we should adhere to the font weight guidance outlined in the editor so thank you for the PR!

Unfortunately, I will have to request changes as this repository uses [catppuccin/whiskers](https://github.com/catppuccin/whiskers) to generate the theme files edited in this PR. I totally appreciate that this isn't documented yet at the organisational level so super sorry! 

What you'll need to do is edit the [xcode.tera](https://github.com/catppuccin/xcode/blob/main/xcode.tera) file with your relevant changes and then run `whiskers xcode.tera` to generate the changes for all the `.xcolortheme` files.

**Comment by lilidotshi** [comment]
> Hey 👋,
> 
> I think we should adhere to the font weight guidance outlined in the editor so thank you for the PR!
> 
> Unfortunately, I will have to request changes as this repository uses [catppuccin/whiskers](https://github.com/catppuccin/whiskers) to generate the theme files edited in this PR. I totally appreciate that this isn't documented yet at the organisational level so super sorry!
> 
> What you'll need to do is edit the [xcode.tera](https://github.com/catppuccin/xcode/blob/main/xcode.tera) file with your relevant changes and then run `whiskers xcode.tera` to generate the changes for all the `.xcolortheme` files.

Can do will fix it up.

**Comment by lilidotshi** [comment]
@sgoudham changes made to xcode.tera, and whiskers xcode.tera run

**Review by sgoudham — APPROVED** [review]
Great, thank you for the PR!

**Pull request merged**
